// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gelbpmbjnfgalabzuwcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlbGJwbWJqbmZnYWxhYnp1d2NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5MjQ0NzksImV4cCI6MjA4OTUwMDQ3OX0.rFdyua14RnlqsQKdwxMGdlV0ROPHuqmdN7LIJgNkx8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});